name: buildx

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: parker-hemphill/godaddy-dns-updater:latest
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: parker-hemphill/godaddy-dns-updater:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
