name: buildx

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      -
        uses: actions/checkout@v2
        name: Check out code
      -
        uses: docker/setup-qemu-action@v1
        name: Set up QEMU
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
      -
        uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ghcr.io/parker-hemphill/godaddy-dns-updater
          tags: latest
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
